version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    command: ["dotnet", "dev-certs","https","--trust"]  
    ports:
      - "80:80"